import Navbar from "@/components/bars/Navbar";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import BottomBar from "@/components/bars/BottomBar";
import LeftBar from "@/components/bars/LeftBar";
import RightBar from "@/components/bars/RightBar";

export const metadata = {
  title: "Gappe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <section className="flex flex-col w-screen h-screen bg-neutral-900">
        <Navbar/>
        <div className="flex h-full overflow-y-auto">
        <LeftBar/>
        {children}
        <RightBar/>
        </div>
        <BottomBar/>
      </section>
    </ClerkProvider>
  );
}
