import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

export const metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <section style={{backgroundColor:"rgb(18,18,18)", overflowX:"auto"}}>
      <ClerkProvider
        appearance={{
          baseTheme: dark,
        }}
      >
        {children}
      </ClerkProvider>
    </section>
  );
}
